### ISSUE TITLE
Replace TSLint with ESLint

### ISSUE THREAD

**Issue by giovannipessiva** [giovannipessiva/l4w#14] opened 2020-10-19 12:07 UTC
TSLint has been deprecated in favor of ESLint: https://github.com/palantir/tslint/issues/4534
Should remove TSLint from the Grunt script and replace it with ESLint, maitaining the rules defined in the TSLint configuration file

**Comment by creativenull** [comment] 2020-10-20 03:22
Hey! Mind if I do this?

**Comment by giovannipessiva** [comment] 2020-10-20 07:07
Hi, I have assigned the issue to you, thanks!

**Comment by creativenull** [comment] 2020-10-21 00:40
Thanks! I'm new to moving from tslint to eslint, so I googled around [to find this guide](https://code.visualstudio.com/api/advanced-topics/tslint-eslint-migration). I was successfully able to get it to lint with eslint, but there were a couple problems that was not addressed in tslint and generated errors and warning in the project:

+ Indentation - eslint likes to keep the indents to 2 spaces but all your ts files have 4 spaces of indent. There was no indication of how many spaces in `tslint.json`. So the question would be to change the eslint rule to 4 spaces? Or just turn off those errors?
+ JSdoc - eslint required couple of the docstrings to have a newline. It's just in a couple files not all, I believe it was 4 files in total. Should I turn off this warning? Or should I keep it and adjust those files accordingly?

**Comment by giovannipessiva** [comment] 2020-10-21 06:40
- Indentation: try adding this to eslint config file (see: https://stackoverflow.com/a/48906878/2700039)
`"indent": ["error", 4]`
- JSdoc: keep the warning, I'll check the files later.

Thanks!!

**Comment by creativenull** [comment] 2020-10-21 16:12
Ok so I adjusted the indent, I used `"@typescript-eslint/indent": ["error", 4]` as recommended instead of `indent` but I still get indent errors. Which makes sense checking those files (where spaces are 5 instead of 4), so I'm guessing it works as intended just more strict. Will this be good enough for the PR?

I tried with `indent` before and I got more errors (~800 w/ indent vs ~500 w/ typescript-indent). So it would be better to just stick with `@typescript-eslint/indent` rule instead?

> JSdoc: keep the warning, I'll check the files later.

I've changed JSdoc from error to warning 👍

**Comment by giovannipessiva** [comment] 2020-10-21 21:09
Mmh I see, I should probabily disable the rule then but I will think on it, thanks for the analysis!

Send the PR, I'll be happy to merge it :-)

**Closed as completed** 2020-10-21 21:53 UTC
Labels: enhancement, help wanted, hacktoberfest
